# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: xenial
cache: packages

r_packages:
  - pkgdown
  - here
  - whoami

r_github_packages:
  - r-lib/covr

r:
  - oldrel
  - release
  - devel

env:
  global:
    - PERLBREW_ROOT=/home/travis/perl5/perlbrew
    - NOT_CRAN=true

before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

after_success:
  - export CI_BRANCH=$TRAVIS_BRANCH
  - export CI_NAME=travis-ci
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'Sys.setenv("R_COVR_SRCDIR"=here::here()); covr::coveralls()'

before_deploy:
  - which perlbrew
  - which cpanm
  - perlbrew list
  - Rscript -e 'withr::with_temp_libpaths(action = "prefix", code = { devtools::install(pkg = ".", reload = FALSE); pkgdown::build_site(pkg = "."); })'
  - touch gh-pages/.nojekyll

notifications:
  email: false
deploy:
  strategy: git
  provider: pages
  keep_history: true
  local_dir: gh-pages
  target_branch: gh-pages
  committer_from_gh: true
  github_token: $GITHUB_PAT
  on:
    branch: master
    repo: kiwiroy/perlbrewr
    condition: $TRAVIS_R_VERSION_STRING = "release"
